# Generated by Django 5.0.4 on 2024-04-22 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrualSettings',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_referral', models.IntegerField(default=0)),
                ('for_referral_code_owner', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='number',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='BalanceOperation',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('referral', 'Referral')], db_index=True, max_length=32, null=True)),
                ('sum', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=128)),
                ('previous_balance', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='balance_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='referral_system.balanceoperation'),
        ),
    ]
