# Generated by Django 5.0.4 on 2024-04-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_code',
            field=models.CharField(db_index=True, default=1234, max_length=4),
            preserve_default=False,
        ),
    ]
